name: Update RSS Feed

# Trigger the workflow on a schedule and on manual dispatch
on:
  schedule:
    - cron: '5 16 * * *'  # Runs at minute 0 of every hour (hourly)
  workflow_dispatch:     # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # You can specify a version like '3.9'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script to generate the RSS feed
      - name: Generate RSS Feed
        run: |
          python scripts/custom_rss_feed.py

      # Step 5: Configure Git for committing
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Commit and push changes if there are any
      - name: Commit and Push if Changed
        run: |
          git add custom_quick_transmigration_feed.xml
          # Check if there are changes to commit
          if ! git diff --cached --quiet; then
            git commit -m "Automated RSS feed update on $(date)"
            git push origin main
          else
            echo "No changes to commit"
          fi

