name: Update RSS Feed

permissions:
  contents: write  # Grants write access to repository contents

on:
  schedule:
    - cron: '5 16 * * *'  # Runs daily at 16:05 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify a version like '3.9' if needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate RSS Feed
        run: |
          python custom_rss_feed.py  # Ensure this path is correct

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push if Changed
        run: |
          git add custom_quick_transmigration_feed.xml
          # Check if there are changes to commit
          if ! git diff --cached --quiet; then
            git commit -m "Automated RSS feed update on $(date)"
            git push origin main
          else
            echo "No changes to commit"
          fi

