name: Update RSS Feed

# Trigger the workflow on a schedule and allow manual triggering
on:
  schedule:
    - cron: '5 16 * * *'  # Runs daily at 16:05 UTC
  workflow_dispatch:       # Allows manual trigger

# Grant the workflow permission to read and write repository contents
permissions:
  contents: write

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository on the 'main' branch with full history
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: main

      # Step 2: Configure Git with a user identity
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 4: Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run the RSS feed generation script
      - name: Generate RSS Feed
        run: |
          python scripts/custom_rss_feed.py  # Ensure this path is correct

      # Step 6: Commit and Push changes if the XML file has been updated
      - name: Commit and Push if Changed
        run: |
          git add custom_quick_transmigration_feed.xml
          if ! git diff --cached --quiet; then
            git commit -m "Automated RSS feed update on $(date) [${GITHUB_SHA}]"
            git push origin main
          else
            echo "No changes found. Nothing to commit."
          fi
