name: Update RSS Feed

on:
  schedule:
    - cron: '5 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 1) Pull first to ensure we're up-to-date
      - name: Pull latest changes with rebase
        run: |
          git pull --rebase origin main

      # 2) Now run the Python script to generate new changes
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate RSS Feed
        run: |
          python scripts/custom_rss_feed.py

      # 3) Commit & push changes
      - name: Add & Commit changes
        run: |
          git add custom_quick_transmigration_feed.xml
          if ! git diff --cached --quiet; then
            git commit -m "Automated RSS feed update on $(date)"
          fi

      - name: Push changes
        run: |
          git push origin main
