name: Update RSS Feed

on:
  schedule:
    - cron: '5 16 * * *'  # Runs daily at 16:05 UTC
  workflow_dispatch:       # Allows manual trigger

permissions:
  contents: write  # Needed so the workflow can push back to the repo

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository on the 'main' branch with full history
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0  # Fetch all history for all branches and tags

      # Step 2: Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the RSS feed generation script
      - name: Generate RSS Feed
        run: |
          python scripts/custom_rss_feed.py  # Ensure this path is correct

      # Step 5: Prepare deploy directory
      - name: Prepare Deploy Directory
        run: |
          mkdir deploy
          cp custom_quick_transmigration_feed.xml deploy/
          echo "" > deploy/.nojekyll  # Prevent Jekyll from processing the XML

      # Step 6: Deploy to GitHub Pages using peaceiris/actions-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          destination_branch: gh-pages
          force: true  # Force push to overwrite gh-pages branch
          commit_message: "Automated RSS feed update on $(date) [${GITHUB_SHA}]"
