name: Update RSS Feed

on:
  # Runs daily at 16:05 UTC
  schedule:
    - cron: '5 16 * * *'
  # Allows you to manually trigger in GitHub Actions
  workflow_dispatch:

permissions:
  contents: write  # Needed so the workflow can push back to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the code on 'main' with full history
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Allows pushing automatically with the built-in GITHUB_TOKEN
          token: ${{ secrets.GITHUB_TOKEN }}
          # Grab entire commit history (not a shallow clone)
          fetch-depth: 0
          # Make sure we are on 'main' instead of a detached HEAD
          ref: main

      # 2) Configure Git identity
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 4) Install Python Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5) Run your feed-generation script
      - name: Generate RSS Feed
        run: python scripts/custom_rss_feed.py

      # 6) Commit and Push changes, if any
- name: Commit and Push if Changed
  run: |
    git add custom_quick_transmigration_feed.xml
    if ! git diff --cached --quiet; then
      git commit -m "Automated RSS feed update on $(date) [${GITHUB_SHA}]"
      git push origin main
    else
      echo "No changes found. Nothing to commit."
    fi
