- name: Checkout Repository
  uses: actions/checkout@v3
  with:
    # Use the built-in token so that push permissions are already set up
    # This is generally better than `persist-credentials: false`
    token: ${{ secrets.GITHUB_TOKEN }}
    fetch-depth: 0
    ref: main   # Make sure we are actually on 'main' (not in a detached HEAD)

- name: Set git identity
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"

# No "git pull --rebase" step here

- name: Install Dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt

- name: Generate RSS Feed
  run: python scripts/custom_rss_feed.py

- name: Commit changed files
  run: |
    git add custom_quick_transmigration_feed.xml
    # only commit/push if file changed
    if ! git diff --cached --quiet; then
      git commit -m "Automated RSS feed update on $(date) [${GITHUB_SHA}]"
      git push origin main
    else
      echo "No changes to commit"
    fi

